connetist/connectist-backend

chat-service/src/main/java/org/example/chatservice/controller/ChatController.java
chat-service/src/main/java/org/example/chatservice/domain/ChatMember.java
chat-service/src/main/java/org/example/chatservice/domain/ChatRoom.java
chat-service/src/main/java/org/example/chatservice/infrastructure/entity/ChatMemberEntity.java
chat-service/src/main/java/org/example/chatservice/infrastructure/entity/ChatRoomEntity.java
chat-service/src/main/java/org/example/chatservice/infrastructure/repository/ChatRepository.java
chat-service/src/main/java/org/example/chatservice/service/ChatService.java
chat-service/src/main/java/org/example/chatservice/service/ChatServiceImpl.java
chat-service/src/test/java/org/example/chatservice/chatRoom/domain/ChatRoomtTest.java
chat-service/src/test/java/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.java

채팅서버 생성, 폴더 분리 및 임의 테스트 코드 
- 요약과 동일 
- https://github.com/kok202/test-code-with-architecture/blob/test/practice-part-2/src/test/java/com/example/demo/mock/FakeUserRepository.java
- 해당 레포를 참조하여 DDD적용ㅁ
close #1

feat : 채팅서버 생성 및 폴더 분리, 임의 테스트코드 작성

---

.github/workflows/chat-service-deployyml

chat-service 배포라인 구축 - 2
chat-service gitignore 수정 후에 배포라인 구축 
이번 patch branch와 내용은 동일

docs : Create chat-service-deployyml

---

.github/workflows/chat-service-deployyml

testcode coverage report를 github action과 연동
작동이 안될 수 도 있음 -> 지속적 수정 필요

docs : testcode coverage report를 github action과 연동

---

.gitattributes

.gitattributes를  통한 표시언어 html 제거
- .gitattributes 생성
- html = false 설정완료 
close #18

docs: .gitattributes를  통한 표시언어 html 제거

---

.github/PULL_REQUEST_TEMPLATE.md

PR 템플릿 수정
- PR 템플릿을 좀 더 직관적이고 체계적으로 수정하였습니다.
close #22

[Chore] PR 템플릿 수정

---

user-service/build.gradle
user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
user-service/src/main/java/com/example/userservice/user/controller/UserController.java
user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
user-service/src/main/java/com/example/userservice/user/domain/User.java
user-service/src/main/java/com/example/userservice/user/domain/UserCreate.java
user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
user-service/src/main/java/com/example/userservice/user/domain/create/UserCreateDto.java
user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
user-service/src/main/java/com/example/userservice/util/clock/ClockHolder.java
user-service/src/main/java/com/example/userservice/util/clock/SystemClockHolder.java
user-service/src/main/java/com/example/userservice/util/id/IdGenerator.java
user-service/src/main/java/com/example/userservice/util/id/IdGeneratorByUUID.java
user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java

user 이메일인증 첫 요청을 보낼 때 발생하는 Joinuser Null 오류 해결
- 굳이 필요하지 않은 부분인 객체 재할당 부분을 없앴습니다. 
- 스레드 동시성 이슈로 인해 발생하는 것 같습니다. 추후 분석하여 해당내용 공유하겠습니다.
- close #26

[FIX] Joinuser Null 오류 해결

---

user-service/build.gradle
user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
user-service/src/main/java/com/example/userservice/user/controller/UserController.java
user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
user-service/src/main/java/com/example/userservice/user/controller/port/JoinUserService.java
user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
user-service/src/main/java/com/example/userservice/user/domain/User.java
user-service/src/main/java/com/example/userservice/user/domain/UserCreate.java
user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
user-service/src/main/java/com/example/userservice/user/domain/create/UserCreateDto.java
user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserConcurrentMapRepository.java
user-service/src/main/java/com/example/userservice/user/infrastructure/join/JoinUserRepository.java
user-service/src/main/java/com/example/userservice/user/service/JoinUserServiceImpl.java
user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
user-service/src/main/java/com/example/userservice/util/clock/ClockHolder.java
user-service/src/main/java/com/example/userservice/util/clock/SystemClockHolder.java
user-service/src/main/java/com/example/userservice/util/id/IdGenerator.java
user-service/src/main/java/com/example/userservice/util/id/IdGeneratorByUUID.java
user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java

1. 유저 로그인을 구현하였습니다.
2. 도메인 구성 요소 ( createdAt : LocalDateTime -> Unix Timestamp, id : UUID)를 변경하였습니다.
- UserCreateDto를 만들어 UserCreate를 구성할 수 있도록 하였고, 인증 시 받아온 JoinUser와 함께 User 도메인을 만들 수 있도록 하였습니다.
- ID generator interface를 만들어 다른 방식의 id도 generate할 수 있도록 하였습니다.
- close #25 
- close #35

[FEAT] 유저 로그인 구현하기 & 도메인 구성 요소 변경하기

---

.gitattributes

github js 코드비율 안보이게 만듬 
요약과 동일

docs : update .gitattributes

---

user-service/build.gradle
user-service/src/main/java/com/example/userservice/config/SecurityConfig.java
user-service/src/main/java/com/example/userservice/user/controller/UserController.java
user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
user-service/src/main/java/com/example/userservice/user/controller/port/UserService.java
user-service/src/main/java/com/example/userservice/user/controller/request/UserUpdateRequest.java
user-service/src/main/java/com/example/userservice/user/controller/response/UserLoginResponse.java
user-service/src/main/java/com/example/userservice/user/domain/User.java
user-service/src/main/java/com/example/userservice/user/domain/UserUpdate.java
user-service/src/main/java/com/example/userservice/user/dto/request/UserDeleteRequest.java
user-service/src/main/java/com/example/userservice/user/dto/request/UserLogin.java
user-service/src/main/java/com/example/userservice/user/dto/request/UserUpdateRequest.java
user-service/src/main/java/com/example/userservice/user/dto/response/UserJoinResponse.java
user-service/src/main/java/com/example/userservice/user/dto/response/UserLoginResponse.java
user-service/src/main/java/com/example/userservice/user/infrastructure/UserEntity.java
user-service/src/main/java/com/example/userservice/user/infrastructure/UserMongoRepository.java
user-service/src/main/java/com/example/userservice/user/infrastructure/UserRepositoryImpl.java
user-service/src/main/java/com/example/userservice/user/infrastructure/join/UserAuthEntity.java
user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
user-service/src/main/java/com/example/userservice/user/service/port/UserRepository.java

User server 구현하기
- User서버 기본 기능을 구현 완료하였습니다.
1. User 회원 가입
2. User log-in (access/refresh token 발급)
3. User 정보 수정
4. User 정보 조회 (id/email)
5. User 삭제
- close #45 
- close #2

[FEAT] user 서버 구현하기

---

chat-service/src/main/java/org/example/chatservice/chatMessage/controller/ChatMessageController.java
chat-service/src/main/java/org/example/chatservice/chatMessage/domain/ChatMessage.java
chat-service/src/main/java/org/example/chatservice/chatMessage/dto/CreateChatMessageRequest.java
chat-service/src/main/java/org/example/chatservice/chatMessage/dto/addChatMessageRequest.java
chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageMongoRepository.java
chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageRepository.java
chat-service/src/main/java/org/example/chatservice/chatMessage/infrastructure/repository/ChatMessageRepositoryImpl.java
chat-service/src/main/java/org/example/chatservice/chatMessage/service/ChatMessageService.java
chat-service/src/main/java/org/example/chatservice/chatMessage/service/ChatMessageServiceImpl.java
chat-service/src/main/java/org/example/chatservice/chatRoom/service/ChatRoomServiceImpl.java
chat-service/src/main/java/org/example/chatservice/error/ResultCode.java
chat-service/src/test/java/org/example/chatservice/chatMessage/domain/ChatMessageDomainTest.java
chat-service/src/test/java/org/example/chatservice/chatRoom/controller/ChatControllerTest.java
chat-service/src/test/java/org/example/chatservice/chatRoom/domain/ChatDomainTest.java
chat-service/src/test/java/org/example/chatservice/chatRoom/service/ChatRoomServiceTest.java
chat-service/src/test/java/org/example/chatservice/mock/FakeChatRoomRepository.java
chat-service/src/test/java/org/example/chatservice/mock/TestContainer.java

채팅메세지 서비스, 컨트롤러, 인프라 구축
채팅메세지의 서비스, 컨트롤러, 인프라에 해당하는 부분들을 구축
-> 전체적인 틀은 채팅방과 동일
close #55

[FEAT] 채팅메세지 서비스, 컨트롤러, 인프라 구축

---

user-service/src/main/java/com/example/userservice/user/domain/User.java
user-service/src/main/java/com/example/userservice/user/domain/create/UserCreate.java
user-service/src/main/java/com/example/userservice/user/infrastructure/TokenRepositoryImpl.java
user-service/src/main/java/com/example/userservice/user/infrastructure/entity/TokenEntity.java
user-service/src/main/java/com/example/userservice/util/exception/ErrorCode.java
user-service/src/test/java/com/example/userservice/user/domain/UserTest.java
user-service/src/test/java/com/example/userservice/user/mock/FakeRedisRepository.java
user-service/src/test/java/com/example/userservice/user/mock/FakeUserDigitRepository.java
user-service/src/test/java/com/example/userservice/user/mock/FakeUserRepository.java
user-service/src/test/java/com/example/userservice/user/mock/TestContainer.java
user-service/src/test/java/com/example/userservice/user/service/JoinUserServiceImplTest.java

User Join Service의 테스트를 구현합니다.
- Service 테스트를 구현하기 위한 Fake Repository를 구현하였습니다.
- Mock으로 사용하지 않지만, 있어야하는 객체를 구현하였습니다.
- 각 테스트가 spring으로부터 독립적이도록 구현하였습니다.
- close #62 
- 차후 잘못된 case에 대해서도 test를 진행하겠습니다.

[FEAT] User Join Service 테스트 구현하기

---

.github/workflows/chat-service-deploy.yml

[DEPLOY] Update chat-service-deploy.yml

---

user-service/src/main/java/com/example/userservice/user/dto/request/UserLoginRequest.java
user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
user-service/src/test/java/com/example/userservice/user/mock/FakeUserRepository.java
user-service/src/test/java/com/example/userservice/user/service/UserServiceImplTest.java

유저서버 서비스 test 구현을 완료하였습니다.
- Mockito를 이용하여 spring boot에 독립적인 test를 구현하였습니다.
- 차후 예외 발생 상황에 대한 test도 구현되어야 합니다.
- close #68

[FEAT] 유저서버 서비스 test 구현 완료

---

user-service/src/main/java/com/example/userservice/user/controller/UserController.java
user-service/src/main/java/com/example/userservice/user/controller/UserCreateController.java
user-service/src/main/java/com/example/userservice/user/dto/request/RequestCheck.java
user-service/src/main/java/com/example/userservice/user/dto/request/UserCreateRequest.java
user-service/src/main/java/com/example/userservice/user/dto/request/UserDeleteRequest.java
user-service/src/main/java/com/example/userservice/user/dto/request/UserLoginRequest.java
user-service/src/main/java/com/example/userservice/user/service/UserServiceImpl.java
user-service/src/main/java/com/example/userservice/util/certification/CertificationDigitHolder.java
user-service/src/test/java/com/example/userservice/user/domain/UserTest.java
user-service/src/test/java/com/example/userservice/user/dto/request/RequestCheckTest.java
user-service/src/test/java/com/example/userservice/user/mock/FakeUserRepository.java
user-service/src/test/java/com/example/userservice/user/service/UserServiceImplTest.java
user-service/src/test/java/com/example/userservice/util/certification/CertificationDigitHolderTest.java

User 서버 controller에서 parameter 검증하기
- controller에서 parameter를 검증할 수 있도록 하였습니다.
- userservice.user.dto 패키지에 RequestCheck 클래스를 구현하였습니다.
`public void check() {
Field[] fields = targetObject.getClass().getDeclaredFields();
for (Field field : fields) {
field.setAccessible(true);
try {
if (field.get(targetObject) == null) {
throw new GlobalException(ErrorCode.INVALID_INPUT);
}
} catch (IllegalAccessException e) {
throw new GlobalException(ErrorCode.INTERNAL_SERVER_ERROR);
}
}
를 추가하여서 null인지 확인하였습니다.
- test를 통해 해당 메서드의 동작을 검증하였습니다.
- "== null 대신 .isNull() 메서드를 사용하는것도 고려해야합니다."
- close #73

[FEAT] User 서버 controller에서 parameter 검증하기

---

README.md

배포 파이프 라인  + 아키텍처 ReadME 추가
아키텍처 구성도 + 배포라인 그림으로 만들어서 Readme에 추가하였음

[DOCS] 배포 파이프 라인  + 아키텍처 ReadME 추가

---

board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java

- Board-service StarEntity merge conflict 해결
- conflict 해결 
- 내용을 적어주세요.

[FIX] Board-service StarEntity merge conflict 해결

---

.github/workflows/board-service-deploy.yml
.github/workflows/chat-service-deploy.yml
board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/StarEntity.java
k8s/board-service/deployment.yaml
k8s/board-service/service.yaml

- board-service, chat-service CI 파이프라인 수정 
- 기존의 방식 : EC2에서 직접 접속하여 docker update 하는 방식
- 현재의 방식 : argoCD를 통해서 원격으로 manifest 파일을 트래킹하여 수정하는 방식 
-그림 참고

[DEPLOY] board-service, chat-service CI 파이프라인 수정 

---

.github/workflows/board-service-deploy.yml
.github/workflows/chat-service-deploy.yml
k8s/chat-service/deployment.yaml
k8s/chat-service/service.yaml

- chat-service CI/CD yaml 파일 구축
- board-service와 동일하니 아래 PR 참조 바람 
- board-service와 동일

[DEPLOY]: chat-service CI/CD yaml 파일 구축

---

board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java

- board-service CI test
- CI 테스트입니다

[DEPLOY] board-service CI test

---

.github/workflows/board-service-deploy.yml
.github/workflows/chat-service-deploy.yml

- chat-service , board-service CI jobs-build-runs-on 변경
- ubuntu -> ubuntu-latest 로 변경 
- 내용을 적어주세요.

[DEPLOY] chat-service , board-service CI jobs-build-runs-on 변경

---

board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java

- board-service ci test -2
- board-service ci test 입니다 
- 내용을 적어주세요.

[DEPLOY] : board-service ci test -2

---

.github/workflows/board-service-deploy.yml
board-service/Dockerfile

- Github actions -> git push origin HEAD:main 추가
- Detached Branch 오류 발생
- 내용을 적어주세요.

[DEPLOY] Github actions -> git push origin HEAD:main 추가

---

.github/workflows/board-service-deploy.yml
board-service/src/test/java/org/example/boardservice/lab/service/LabServiceTest.java

내용을 적어주세요.
- 코드 작성 의도를 포함한 수정 내용을 적어주세요.
- 내용을 적어주세요.

deploy : board-service 재배포 테스트

---

.github/workflows/chat-service-deploy.yml
eureka-service/src/main/resources/application.yaml

- Eureka-service 생성
- Eureka-service 생성함
- 추가적으로, Chat-service-deploy.yml의 파일 수정을 통한 안전한 CI 라인 구축
- Eureka-server 포트는 8761 번입니다 
- close #105

[FEAT] Eureka-service 생성

---

user-service/src/main/java/com/example/userservice/user/infrastructure/entity/UserEntity.java
user-service/src/main/resources/data.sql

Admin user sql제작
- user service를 실행하면 admin user가 바로 db로 들어갈 수 있도록 하였습니다.
- close #111

[FEAT] Admin user sql제작

---

board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
board-service/src/main/java/org/example/boardservice/board/controller/CommentController.java
board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
board-service/src/main/java/org/example/boardservice/board/domain/Recomment.java
board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardDeleteRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardLikeRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/comment/CommentDeleteRequest.java
board-service/src/main/java/org/example/boardservice/board/infrastructure/entity/RecommentEntity.java
board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/comment/CommentRepositoryImpl.java
board-service/src/main/java/org/example/boardservice/board/service/board/BoardService.java
board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
board-service/src/main/java/org/example/boardservice/board/service/comment/CommentService.java
board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
board-service/src/main/java/org/example/boardservice/board/service/lab/LabServiceImpl.java
board-service/src/main/resources/application.yml
board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java

- board-service 전체 수정
- board-service의 domain,service,controller 부분 검토 후 필요한 부분 전체 수정
- 수정되지 않은 부분은 따로 Issue에 남겼음
- api uri 경로수정
- domain 생성시 잘못된 UUID로 만들어지는 부분들 수정
- userId 검증로직 추가

[FIX] board-service 전체 수정

---

board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
board-service/src/main/java/org/example/boardservice/board/domain/Lab.java
board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
board-service/src/main/java/org/example/boardservice/board/service/lab/LabServiceImpl.java

내용을 적어주세요.
- 코드 작성 의도를 포함한 수정 내용을 적어주세요.
- 내용을 적어주세요.

[FIX] board-service 전체 수정 -2

---

board-service/src/test/java/org/example/boardservice/lab/domain/LabDomainTest.java
board-service/src/test/java/org/example/boardservice/lab/service/LabServiceTest.java
board-service/src/test/java/org/example/boardservice/mock/TestContainer.java

내용을 적어주세요.
- 코드 작성 의도를 포함한 수정 내용을 적어주세요.
- 내용을 적어주세요.

fix: 게시판서비스 테스트 수정

---

user-service/.gitignore

내용을 적어주세요.
- 코드 작성 의도를 포함한 수정 내용을 적어주세요.
- 내용을 적어주세요.

fix: gitignore에 dsstore추가하기

---

board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardDeleteRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardLikeRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/board/BoardRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/comment/create/CommentRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/comment/create/RecommentRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/comment/delete/CommentDeleteRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/comment/delete/RecommentDeleteRequest.java
board-service/src/main/java/org/example/boardservice/board/dto/request/comment/like/CommentLikeRequest.java
board-service/src/main/java/org/example/boardservice/board/service/board/BoardService.java
board-service/src/main/java/org/example/boardservice/board/service/board/BoardServiceImpl.java
board-service/src/main/java/org/example/boardservice/board/service/comment/CommentService.java
board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
board-service/src/test/java/org/example/boardservice/board/domain/BoardDomainTest.java
board-service/src/test/java/org/example/boardservice/board/service/BoardServiceTest.java
board-service/src/test/java/org/example/boardservice/comment/domain/CommentDomainTest.java
board-service/src/test/java/org/example/boardservice/comment/service/CommentServiceTest.java
board-service/src/test/java/org/example/boardservice/mock/FakeBoardRepository.java
board-service/src/test/java/org/example/boardservice/mock/FakeCommentRepository.java

- 게시글 도메인, 서비스 테스트
- 게시글의 도메인, 서비스테스트를 진행하였습니다
- BoardResponse 이라는 객체를 서비스에서 바로 Return할 필요는 없을 것 같아서 수정하였습니다
- Service에서는 Response를 반환하는것이 아닌, 도메인을 최대한 반환하도록 하고 Controller에서는 이를 조합하여 Response객체로 만든 후에 반환하는게 좋을것 같습니다
- Domain을 직접 Return하는 것 말고 DTO로 Return하는 방법도 고려해봐야 할 것 같습니다.

[TEST] 게시글 도메인, 서비스 테스트

---

user-service/src/main/java/com/example/userservice/user/controller/token/TokenController.java
user-service/src/main/java/com/example/userservice/user/controller/user/UserController.java
user-service/src/main/java/com/example/userservice/user/dto/response/token/TokenResponse.java
user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenService.java
user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenServiceImpl.java

- User Service Health Check추가하기 
- Refresh 만료 시 TokenResponse로 응답하기
- health check controller를 만들었습니다.
- gateway에서 refresh가 만료되었을 때 tokenResponse로 응답을 받을 수 있습니다.
- close #140

[FEAT] User Service Health Check추가하기 

---

apigateway-service/build.gradle
apigateway-service/src/main/java/org/example/apigatewayservice/ApigatewayServiceApplication.java
apigateway-service/src/main/java/org/example/apigatewayservice/feign/TokenClient.java
apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
apigateway-service/src/main/java/org/example/apigatewayservice/response/TokenResponse.java
apigateway-service/src/main/resources/application.yaml
user-service/src/main/java/com/example/userservice/util/token/JwtUtil.java

- Authorization Filter의 JWT 인증로직 추가 
- gateway에서 인증로직 추가
- token 만료시간 변경
- Filter코드 어렵지 않으니 보시면 아실겁니다

[FEAT] Authorization Filter의 JWT 인증로직 추가 

---

apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
apigateway-service/src/main/java/org/example/apigatewayservice/filter/StickySessionFilter.java
apigateway-service/src/main/resources/application.yaml
user-service/src/main/java/com/example/userservice/user/domain/user/User.java
user-service/src/main/java/com/example/userservice/user/domain/user/value/UserDegree.java
user-service/src/main/java/com/example/userservice/user/domain/user/value/UserMajor.java
user-service/src/main/java/com/example/userservice/user/domain/user/value/UserSex.java
user-service/src/main/java/com/example/userservice/user/domain/user/value/UserStatus.java
user-service/src/main/java/com/example/userservice/user/dto/request/user/UserCreateRequest.java
user-service/src/main/java/com/example/userservice/user/service/token/JwtTokenServiceImpl.java
user-service/src/main/java/com/example/userservice/user/service/user/mail/UserCertificationService.java
user-service/src/test/java/com/example/userservice/user/service/UserServiceImplTest.java

cloud gateway에서 cookie업데이트 하기
- 기존 cookie를 여러개 넣던 코드가 매우 불편해서 cookie를 업데이트하게 만들었습니당
- #144

[REFACTOR]: cloud gateway에서 cookie업데이트 하기

---

apigateway-service/src/main/java/org/example/apigatewayservice/filter/AuthorizationHeaderFilter.java
apigateway-service/src/main/resources/application.yaml
board-service/build.gradle
board-service/src/main/java/org/example/boardservice/BoardServiceApplication.java
board-service/src/main/java/org/example/boardservice/board/controller/BoardController.java
board-service/src/main/java/org/example/boardservice/board/infrastructure/repository/board/BoardRepositoryImpl.java
board-service/src/main/java/org/example/boardservice/board/service/comment/CommentServiceImpl.java
board-service/src/main/java/org/example/boardservice/error/GlobalException.java
board-service/src/main/java/org/example/boardservice/error/ResultCode.java
board-service/src/main/java/org/example/boardservice/utils/PortListener.java
board-service/src/main/resources/application.yml
board-service/src/test/java/org/example/boardservice/comment/service/CommentServiceTest.java
chat-service/build.gradle
chat-service/src/main/java/org/example/chatservice/ChatServiceApplication.java
chat-service/src/main/resources/application.yaml
user-service/src/main/java/com/example/userservice/user/controller/user/UserController.java

board,chat service eureka client로 등록하고 api-gateway에 연결하기
- 각 서비스들을 eureka client로 등록하고 gateway에서 auth필터를 통해 호출하도록 변경하였습니다.
- health check 완료하였습니다.
- close #151
- close #152

[FEAT] board,chat service eureka client로 등록하고 api-gateway에 연결하기

---

eureka-service/src/main/java/org/example/eurekaservice/EurekaServiceApplication.java
user-service/src/main/java/com/example/userservice/user/domain/user/UserJoin.java
user-service/src/main/java/com/example/userservice/user/service/user/join/JoinUserServiceImpl.java
user-service/src/test/java/com/example/userservice/user/domain/user/UserJoinTest.java

UserJoin domain unit test를 제작
- UserJoin domain에 대한 unit test를 제작한다.
- User domain에 대한 Unit test를 제작한다.
- #157

[TEST] UserJoin domain unit test를 제작한다

---

user-service/src/main/java/com/example/userservice/user/service/user/UserServiceImpl.java
user-service/src/test/java/com/example/userservice/user/infrastructure/entity/UserEntityTest.java
user-service/src/test/java/com/example/userservice/user/mock/FakeUserRepository.java
user-service/src/test/java/com/example/userservice/user/service/UserServiceImplTest.java
user-service/src/test/java/com/example/userservice/user/service/user/join/JoinUserServiceImplTest.java

user-service의 userService unit test구현하기
- user domain에 대한 userService의 unit test를 구현하였습니다.
- userEntity에 대한 unit test를 구현하였습니다.
- close #159

[TEST] user-service의 userService unit test구현하기
